### ISSUE TITLE
Get Started button on homepage 404

### ISSUE THREAD

**Issue by SinbadEV** [refinedmods/refinedstorage-website#40]
![Screenshot_20200613-095344_Chrome](https://user-images.githubusercontent.com/1950416/84570642-c4e28f00-ad5c-11ea-8de0-601611e62b1a.jpg)
Get Started button goes to https://refinedmods.com/refined-storage/wiki/getting-started

Looks like the ".html" was omitted because https://refinedmods.com/refined-storage/wiki/getting-started.html works fine.

**Comment by SinbadEV** [comment]
![Screenshot_20200613-100622_Chrome](https://user-images.githubusercontent.com/1950416/84570778-9a450600-ad5d-11ea-8d46-2ab2d1315c7f.jpg)
Sorry. Specifically this button on https://refinedmods.com/refined-storage/

**Comment by raoulvdberge** [comment]
Yes, just noticed it too! You are posting in the wrong repo however.

Fixed in https://github.com/refinedmods/website/commit/142a0284f1950b05b477cb356b5960422fb8af21
